spring:
  application:
    name: diary
  datasource:
    hikari:
      maximum-pool-size: 4
      minimum-idle: 1
      connection-timeout: 2000
  profiles:
    default: local
server:
  tomcat:
    threads:
      max: 32
      min-spare: 2
